---
apiVersion: v1
kind: Pod
metadata:
  name: multinginx
spec:
  containers:
    - name: nginx1
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8085
      imagePullPolicy: Always
    - name: nginx2
      image: nginx
      ports:
        - containerPort: 85
          hostPort: 8086
      imagePullPolicy: Always

