---
apiVersion: v1
kind: Pod
metadata:
  name: nginxmongo
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      imagePullPolicy: Always

    - name: mongo
      image: mongo
      ports: 
        - containerPort: 7501
      imagePullPolicy: Always

