---
apiVersion: v1
kind: Pod
metadata:
  name: nginxmongo1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 9080
      imagePullPolicy: Always

    - name: mongo
      image: mongo
      ports: 
        - containerPort: 27017
          hostPort: 9090
      imagePullPolicy: Always

