---
apiVersion: v1
kind: Pod
metadata:
  name: nginxportfrwd
spec:
  containers:
    - name: nginx1
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8090
      imagePullPolicy: Always

